app/models/employee.py
import datetime
import logging
from dataclasses import dataclass

from flask import flash
from sqlalchemy.exc import SQLAlchemyError

from app import db

@dataclass
class Employee(db.Model):
    employee_id: int = db.Column(db.Integer, primary_key = True)
    email: str = db.Column(db.String(150), unique = True)
    first_name: str = db.Column(db.String(150))
    last_name: str = db.Column(db.String(150))
    team_name: str = db.Column(db.String(150))
    role:str = db.Column(db.String(150))
    location: str = db.Column(db.String(150))
    date_joined: datetime.datetime = db.Column(db.Date)
    created: datetime.datetime = db.Column(db.DateTime, default=datetime.datetime.now())

def find_employee_by_id(employee_id):
    try:
        retrieved_employee = Employee.query.get(employee_id)
        return retrieved_employee
    except SQLAlchemyError as err:
        db.session.rollback()
        logging.error('Error occurred whilst querying the database {err}')

def find_employee_by_email(email):
    try:
        retrieved_employee = Employee.query.filter_by(email=email).first()
        return retrieved_employee
    except SQLAlchemyError as err:
        db.session.rollback()
        logging.error('Error occurred whilst querying the database {err}')

def create_employee(email: str, first_name: str, last_name: str, team_name: str, role: str, location: str, date_joined: datetime):
    try:
        new_employee = Employee(email=email, first_name=first_name, last_name=last_name,
                                team_name=team_name, role=role, location=location, date_joined=date_joined)
        db.session.add(new_employee)
        db.session.commit()
    except SQLAlchemyError as err:
        db.session.rollback()
        logging.error('Unable to create employee: %s, {err}', first_name)
        flash('Unable to create employee', category='error')
    else:
        logging.info('Employee %s created successfully', first_name)
        flash('Employee added successfully', category='success')

def update_employee(employee_id, updated_employee):
    try:
        db.session.query(Employee).filter_by(employee_id=employee_id).update(updated_employee)
        db.session.commit()
    except SQLAlchemyError as err:
        db.session.rollback()
        logging.error('Unable to update employee: %s, {err}', updated_employee['email'])
        flash('Unable to update employee', category='error')
    else:
        logging.info('Employee: %s successfully updated', updated_employee['email'])
        flash('Employee successfully updated')

def delete_employee(employee_id):
    retrieved_employee = find_employee_by_id(employee_id)
    if retrieved_employee:
        try:
            db.session.delete(retrieved_employee)
            db.session.commit()
        except SQLAlchemyError as err:
            db.session.rollback()
            logging.error('Unable to delete employee: %s {err}', retrieved_employee['email'])
            flash('Unable to delete employee', category='error')
        else:
            logging.info('Employee: %s deleted successfully', retrieved_employee.first_name)
            flash('Employee deleted successfully', category='success')
    else:
        flash('Employee cannot be deleted as they do not exist', category='error')

app/employee/forms.py
from flask_wtf import FlaskForm
from wtforms import validators, StringField, EmailField, SelectField, DateField
from wtforms.validators import DataRequired, InputRequired, ValidationError

class EmployeeForm(FlaskForm):
    first_name = StringField('First name', [DataRequired(), validators.Length(min=2, max=70), validators.Regexp('^[a-zA-Z\- ]+$', message='First name must only contain alphabetic characters and hyphens')])
    last_name = StringField('Last name', [DataRequired(), validators.Length(min=1, max=70), validators.Regexp('^[a-zA-Z\- ]+$', message='Last name must only contain alphabetic characters hyphens')])
    email = EmailField('Email', [DataRequired()])
    team_name = StringField('Team Name', [DataRequired(), validators.Length(min=3, max=30), validators.Regexp('^[a-zA-Z\- ]+$', message='Team name must only contain alphabetic characters hyphens')])
    role = StringField('Role', [DataRequired(), validators.Length(min=4, max=30), validators.Regexp('^[a-zA-Z ]+$', message='Role must only contain alphabetic characters')])
    location = SelectField('Location',[InputRequired()], choices=[('Please Select','Please Select'), ('Germany', 'Germany'), ('India', 'India'), ('Poland', 'Poland'), ('United Kingdom', 'United Kingdom'), ('United States', 'United States')])
    date_joined = DateField('Date Joined', [InputRequired()])

    def validate_location(self, field):
        if field.data == 'Please Select':
            raise ValidationError('Please select a location')

app/employee/__init__.py
from flask import Blueprint

employee = Blueprint('employee', __name__)

from app.employee import routes

app/employee/routes.py
from flask import render_template, request, flash, redirect, url_for, jsonify
from flask_login import login_required, current_user

from app import db
from app.employee import employee
from app.employee.forms import EmployeeForm
from app.models.employee import Employee, find_employee_by_id, find_employee_by_email, create_employee, update_employee, delete_employee

@login_required
@employee.route('/create', methods=['GET', 'POST'])
def create():
    form = EmployeeForm()
    if request.method == 'POST':
        retrieved_employee = find_employee_by_email(form.email.data)

        if retrieved_employee:
            flash('An employee with this email address already exists within the system', category='error')
        elif form.validate_on_submit():
            create_employee(form.email.data, form.first_name.data, form.last_name.data, form.team_name.data, form.role.data, form.location.data, form.date_joined.data)

    return render_template('employees/add-employee.html', user=current_user, form=form)

@login_required
@employee.route('/update', methods=['POST', 'GET'])
def update():
    form = EmployeeForm()
    employee_id = request.args.get('employee_id')
    retrieved_employee = find_employee_by_id(employee_id)
    if request.method == 'POST' and form.validate_on_submit():
        updated_employee = form.data
        updated_employee.pop('csrf_token', None)
        if retrieved_employee:
            update_employee(employee_id, updated_employee)
            redirect(url_for('views.dashboard'))
        else:
            flash('Employee cannot be updated as they do not exist', category='error',)

    return render_template('employees/update-employee.html', user = current_user, employee = retrieved_employee, form = form)

@login_required
@employee.route('/delete', methods=['GET', 'POST'])
def delete():
    if request.method == 'GET' and current_user.is_admin:
        employee_id = request.args.get('employee_id')
        delete_employee(employee_id)

    return redirect(url_for('views.dashboard'))

# see if i need these endpoints, i might remove.
@login_required
@employee.route('/fetch_all', methods=['GET'])
def fetch_all_employees():
    return jsonify(db.session.query(Employee).all())

app/templates/employees/add-employee.html
{% extends "base.html" %}

{% block content %}

{% from "_formhelpers.html" import render_field %}

<div class="container mt-2">
    <h4>Add Employee</h4>
    <form method="POST">
    {{ form.csrf_token() }}
    <dl>
        {{ render_field(form.first_name, class='form-control mt-4', placeholder='First name') }}
        {{ render_field(form.last_name, class='form-control', placeholder='Last name') }}
        {{ render_field(form.email, class='form-control', placeholder='Email address') }}
        {{ render_field(form.date_joined, class='form-control') }}
        {{ render_field(form.team_name, class='form-control', placeholder='Team name') }}
        {{ render_field(form.role, class='form-control', placeholder='Role') }}
        <div class="form-floating">
            <select id="{{ form.location.id }}" name = "{{ form.location.name }}" class="form-select">
                {% for option in form.location %}
                {% if option.data == 'Please Select' %}
                <option value ="{{ option.data }}" disabled selected hidden>{{ option.data }}</option>
                {% else %}
                <option value ="{{ option.data }}">{{ option.data }}</option>
                {% endif %}
                {% endfor %}
            </select>
            <label for="{{ form.location.id }}">{{ form.location.label }}</label>
        </div>
    </dl>
    <div class="d-grid gap-2 text-center">
        <button class="btn btn-primary" type="submit">Add Employee</button>
    </div>
</form>
</div>

{% endblock %}

app/templates/employees/update-employee.html
{% extends "base.html" %}

{% block content %}

{% from "_formhelpers.html" import render_field %}

<div class="container mt-2">
    <h4> Update Employee</h4>
    <form action="{{ url_for('employee.update', employee_id = employee.employee_id) }}" method="POST">
      {{ form.csrf_token() }}
      <dl>
        {{ render_field(form.first_name, class='form-control mt-4', placeholder='First name', value=employee.first_name) }}
        {{ render_field(form.last_name, class='form-control', placeholder='Last name', value=employee.last_name) }}
        {{ render_field(form.email, class='form-control', placeholder='Email address', value=employee.email, readonly=true) }}
        {{ render_field(form.date_joined, class='form-control', value=employee.date_joined)}}
        {{ render_field(form.team_name, class='form-control', placeholder='Team name', value=employee.team_name) }}
        {{ render_field(form.role, class='form-control', placeholder='Role', value=employee.role)}}

        <div class="form-floating">
          <select id="{{ form.location.id }}" name ="{{ form.location.name }}" class="form-select">
            {% for option in form.location %}
            {% if option.data == employee.location %}
            <option value ="{{ option.data }}" selected>{{ option.data }}</option>
            {% elif option.data != 'Please Select'%}
            <option value ="{{ option.data }}">{{ option.data }}</option>
            {% endif %}
            {% endfor %}
          </select>
          <label for="{{ form.location.id }}">{{ form.location.label }}</label>
        </div>
      </dl>
      <div class="d-grid gap-2 text-center">
        <button class="btn btn-primary" type="submit">Update Employee</button>
      </div>
    </form>
</div>

{% endblock %}