app/views.py
from flask import render_template, Blueprint
from flask_login import login_required, current_user

from app import db
from app.employee.forms import EmployeeForm
from app.models.employee import Employee

views = Blueprint('views', __name__)

@views.route('/dashboard')
@login_required
def dashboard():
    form = EmployeeForm()
    returned_data = db.session.query(Employee).all()
    return render_template('grid.html', user=current_user, form=form, list=returned_data)

app/templates/_formhelpers.html
{% macro render_field(field) %}
{% if field.type == 'RadioField'%}
  <dd>
    <dt>{{ field.label }}</dt>
      {{ field(**kwargs)|safe }}

      {% if field.errors %}
    <ul class="list-unstyled">
    {% for error in field.errors %}
      <li class="text-danger">
        <i class="bi bi-exclamation-circle" aria-hidden="true"></i>
        {{ error }}
      </li>
    {% endfor %}
    </ul>
  {% endif %}
</dd>
{% else %}
  <dd>
    <div class="form-floating mb-3">
      {{ field(**kwargs)|safe }}
      {{ field.label }}
      {% if field.errors %}
    <ul class="list-unstyled">
    {% for error in field.errors %}
      <li class="text-danger">
        <i class="bi bi-exclamation-circle" aria-hidden="true"></i>
        {{ error }}
      </li>
    {% endfor %}
    </ul>
  {% endif %}
    </div>
</dd>
{% endif %}
{% endmacro %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdn.datatables.net/2.1.8/css/dataTables.bootstrap5.css"
      crossorigin="anonymous"
    />
  <title>Employee Management System</title>
</head>
<body>

<nav class="navbar navbar-expand-lg bg-body-tertiary navbar-dark bg-dark" >
  <div class="container-fluid">
    <a class="navbar-brand" href="{{ url_for('views.dashboard') }}">Employee Management System</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('views.dashboard') }}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#" data-bs-toggle="modal" data-bs-target="#modallogout">Logout</a>
        </li>
          {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
        </li>
          {% endif %}
      </ul>
      {% if user.is_authenticated %}
        <div class="d-flex justify-content-end text-light">
            <span><i class="bi bi-person fs-4"></i>{{ user.first_name }}</span>
        </div>
        {% endif %}
    </div>
  </div>
</nav>

        <div class="modal fade" id="modallogout" tabindex="-1" aria-labelledby="modelLogoutLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="staticBackdropLabel">Logout confirmation</h1>
                    </div>
                    <div class="modal-body">
                        <div class="text-center">
                            <p>Are you sure you want to logout?</p>
                            <div>
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                <a href="{{url_for('auth.logout')}}"><button type="button" class="btn btn-primary" data-bs-dismiss="modal">Logout</button></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
            <div class="alert {{'alert-danger' if category == 'error' else 'alert-success'}} alert-dismissible fade show" role="alert">
              {{ message }}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
      {% endif %}
    {% endwith %}

  <div class="container">
    {% block content %} {% endblock %}
  </div>


<script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.2/moment.min.js"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.datatables.net/2.1.8/js/dataTables.js"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.datatables.net/2.1.8/js/dataTables.bootstrap5.js"
      crossorigin="anonymous"
    ></script>
    <script
      src="../static/js/index.js"
    ></script>

</body>
</html>

app/templates/grid.html
{% extends "base.html" %}

{% block content %}

{% from "_formhelpers.html" import render_field %}

<div class="container mt-2">
    <div class="bg-light rounded">
        <div class="row">
            <h2>Manage Employees
                <a  class="button btn btn-success float-lg-end" href="{{url_for('employee.create')}}">Add New Employee</a>
            </h2>
        </div>

        <table class="table table-hover table-striped table-light" id="employeeTable">
            <thead class="table-dark">
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Team Name</th>
                <th>Role</th>
                <th>Location</th>
                <th>Date Joined</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for item in list %}
            <tr>
                <td>{{item.first_name}} {{item.last_name}}</td>
                <td>{{item.email}}</td>
                <td>{{item.team_name}}</td>
                <td>{{item.role}}</td>
                <td>{{item.location}}</td>
                <td>{{item.date_joined}}</td>
                <td>
                    <a href="{{url_for('employee.update', employee_id = item.employee_id)}}"><i class="bi bi-pencil fs-4 mx-1"></i></a>
                    {% if user.is_admin %}
                    <a href="/delete/{{item.employee_id}}" data-bs-toggle="modal" data-bs-target="#modeldeleteemployee{{item.employee_id}}"><i class="bi bi-trash fs-4 text-danger mx-1"></i></a>
                    {% endif %}
                </td>
            </tr>
        <div class="modal fade" id="modeldeleteemployee{{item.employee_id}}" tabindex="-1" aria-labelledby="modelDeleteEmployeeLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-body">
                        <div class="text-center">
                            <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-x-circle text-danger" viewBox="0 0 16 16">
                                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16"/>
                                <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708"/>
                            </svg>
                            <h3>Are you sure?</h3>
                            <p>Are you sure you want to delete {{item.first_name}} as an employee. This process cannot be undone</p>
                            <div>
                                <a href="{{url_for('views.dashboard')}}" class="button btn btn-secondary">Cancel</a>
                                <a href="{{url_for('employee.delete', employee_id = item.employee_id)}}" class="button btn btn-danger">Delete</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
        </tbody>
    </table>
    </div>
</div>
{% endblock %}